# Generated by Django 5.0.8 on 2024-08-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='schedule',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='location',
            field=models.CharField(default='TBD', max_length=100),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='meeting_time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
