# Generated by Django 5.0.8 on 2024-08-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_studygroup_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='meeting_time',
            field=models.DateTimeField(),
        ),
    ]
