# Generated by Django 5.0.8 on 2024-08-13 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_studygroup_meeting_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='location',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='meeting_time',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='schedule',
            field=models.ManyToManyField(to='core.schedule'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
