# Generated by Django 5.1 on 2024-08-29 15:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subject_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='test',
            name='subject',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='submitted',
            new_name='submission_status',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='date_received',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='user',
        ),
        migrations.AddField(
            model_name='grade',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.assignment'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='schedule',
            field=models.TextField(default='No schedule provided'),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
