# Generated by Django 5.1 on 2024-09-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_assignment_created_at_assignment_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='user',
        ),
    ]
